version: "3.8"
services:
  yatytb:
    image: ghcr.io/cchrkk/yatytb:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN} # bot token from BotFather
      - ALLOWED_IDS=${ALLOWED_IDS} # Set allowed IDs separated by comma
    volumes:
      - ./cookies.txt:/app/cookies/cookies.txt  # Optional: Only set if cookies needed
