version: "3.8"
services:
  yatytb:
    container_name: yatytb
    image: ghcr.io/cchrkk/yatytb:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN} # REQUIRED: Bot token from BotFather
      - ALLOWED_IDS=${ALLOWED_IDS} # REQUIRED: Set allowed IDs separated by comma
      # - LOG_TO_FILE=false #OPTIONAL: Set to true to log to a file
      # - LOG_FILE_PATH=bot.log #OPTIONAL: Set the path to the log file
    volumes:
      - ./cookies.txt:/app/cookies/cookies.txt # Optional: Only set if cookies needed
    restart: always
    stop_grace_period: 30s
    stop_signal: SIGTERM
