version: "3.8"
services:
  yatytb:
    container_name: yatytb
    image: ghcr.io/cchrkk/yatytb:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_IDS=${ALLOWED_IDS}
    volumes:
      - ./cookies.txt:/app/cookies/cookies.txt
    depends_on:
      - telegram-api  # Dipendenza dal servizio API personalizzato
  telegram-api:
    container_name: yatytb-telegram-api
    # Utilizza l'immagine del bot API di Telegram
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}  # Inserisci il tuo API ID
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}  # Inserisci il tuo API Hash
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "7771:8081"  # Porta per l'API locale
