services:
  yatytb-tg-api:
    container_name: yatytb-tg-api
    image: aiogram/telegram-bot-api:latest
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - yatytb-tg-api-data:/data
    restart: always

  yatytb:
    container_name: yatytb
    image: ghcr.io/cchrkk/yatytb:latest
    depends_on:
      - yatytb-tg-api
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_IDS=${ALLOWED_IDS}
      - BASE_URL=http://yatytb-tg-api:8081/bot{token}
      - MAX_FILE_SIZE_MB=2000
      - LOG_TO_FILE=false
      - LOG_FILE_PATH=bot.log
      - COOKIES_PATH=/app/cookies/cookies.txt
      - DOWNLOAD_DIR=/app/downloads
    volumes:
      - ./cookies.txt:/app/cookies/cookies.txt
    restart: always
    stop_grace_period: 30s
    stop_signal: SIGTERM

volumes:
  yatytb-tg-api-data:
