version: "3.8"
services:
  yatytb:
    container_name: yatytb
    image: ghcr.io/cchrkk/yatytb:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN} # REQUIRED: Bot token from BotFather
      - ALLOWED_IDS=${ALLOWED_IDS} # REQUIRED: Set allowed IDs separated by comma
      # Optional:- LOG_TO_FILE=false
      # Optional:- LOG_FILE_PATH=bot.log
    volumes:
      - ./cookies.txt:/app/cookies/cookies.txt # Optional: Only set if cookies needed
